repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
#      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place]
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.11.1
    hooks:
      - id: validate_manifest
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.8.4
#    hooks:
#      - id: flake8
#        max-line-length: 120
#        additional_dependencies: [flake8-typing-imports==1.10.0]
#  - repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: v1.5.4
#    hooks:
#      - id: autopep8
#  - repo: https://github.com/asottile/setup-cfg-fmt
#    rev: v1.15.1
#    hooks:
#      - id: setup-cfg-fmt
#  - repo: meta
#    hooks:
#      - id: check-hooks-apply
#      - id: check-useless-excludes
#files: ^src/
exclude: ^.*/migrations/.*$
default_language_version:
  python: python3

default_stages: [commit, push]
