
version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    environment:
      - PYTHONBUFFERED=0
    depends_on:
      - redis
      - db
  celery_default:
    build:
      dockerfile: Dockerfile.celery
    container_name: celery_default
    environment:
      - PYTHONBUFFERED=0
    depends_on:
      - redis
      - db
  celery_beat:
    build:
      dockerfile: Dockerfile.celerybeat
    container_name: celery_beat
    environment:
      - PYTHONBUFFERED=0
    depends_on:
      - redis
      - db
      - celery_default
  redis:
    image: redis
    container_name: cache
    ports:
      - "6380:6379"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5455:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
