"""user added field password.

Revision ID: 3e9f122b0a0a
Revises: 551333b08186
Create Date: 2022-12-08 00:35:51.127044
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e9f122b0a0a"
down_revision = "551333b08186"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
