"""user added field.

Revision ID: 90909d88d7e1
Revises: 89c8140a9552
Create Date: 2022-12-07 22:04:54.908807
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "90909d88d7e1"
down_revision = "89c8140a9552"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
